# Generated by Django 5.2.6 on 2026-03-09 16:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default="L'application est en maintenance.")),
                ('global_title', models.CharField(blank=True, max_length=150)),
                ('global_message', models.TextField(blank=True)),
                ('send_to_all_now', models.BooleanField(default=False, verbose_name='🚀 ENVOYER EN TEMPS RÉEL')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modeles/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OffreAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('prix_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_jours', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('total_commande', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACOMPTE_PAYE', 'Acompte payé'), ('TOTALEMENT_PAYE', 'Totalement payé')], default='EN_ATTENTE', max_length=20)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LibelleMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('position_x', models.FloatField(default=0.0, help_text='Position horizontale en % sur le gabarit')),
                ('position_y', models.FloatField(default=0.0, help_text='Position verticale en % sur le gabarit')),
                ('categorie', models.CharField(default='Général', help_text='Ex: Haut, Bas, Accessoire', max_length=50)),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_client', to='core.clientprofile')),
            ],
            options={
                'unique_together': {('client_profile', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ModeleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.commande')),
                ('modele_disponible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modeledisponible')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='modeledisponible',
            name='professional_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='core.professionalprofile'),
        ),
        migrations.AddField(
            model_name='commande',
            name='professional_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_recues', to='core.professionalprofile'),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.offreabonnement')),
                ('professional_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='core.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=22, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professionalprofile')),
            ],
        ),
        migrations.AddField(
            model_name='modeledisponible',
            name='type_vetement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeles_disponibles', to='core.typevetement'),
        ),
        migrations.CreateModel(
            name='ValeurMesureCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_nom', models.CharField(max_length=100)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('article_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_figees', to='core.modelecommande')),
            ],
            options={
                'verbose_name': 'Mesure Figée',
                'verbose_name_plural': 'Mesures Figées',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('derniere_recharge', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type_transaction', models.CharField(choices=[('RECHARGE', 'Recharge'), ('PAIEMENT_ABONNEMENT', 'Abonnement'), ('ACHAT_ARTICLE', 'Achat Article')], max_length=25)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('reference_paiement_externe', models.CharField(max_length=100, unique=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet')),
            ],
            options={
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='MesureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_dynamiques', to='core.clientprofile')),
                ('libelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libellemesure')),
            ],
            options={
                'unique_together': {('client_profile', 'libelle')},
            },
        ),
    ]
