# Generated by Django 5.2.6 on 2026-03-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelecommande',
            name='image_personnalisee',
            field=models.ImageField(blank=True, null=True, upload_to='commandes/custom/'),
        ),
        migrations.AlterField(
            model_name='modelecommande',
            name='modele_disponible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modeledisponible'),
        ),
    ]
