# Generated by Django 5.2.6 on 2026-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_modelecommande_image_personnalisee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Politique de Confidentialité', max_length=200)),
                ('contenu', models.TextField(help_text='Vous pouvez utiliser du HTML simple ici')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politique de Confidentialité',
                'verbose_name_plural': 'Politique de Confidentialité',
            },
        ),
    ]
