# Generated by Django 5.2.6 on 2026-04-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default="Conditions Générales d'Utilisation", max_length=200)),
                ('contenu', models.TextField(help_text="Le contrat entre vous et l'utilisateur")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CGU',
                'verbose_name_plural': 'CGU',
            },
        ),
    ]
