# Generated by Django 5.2.6 on 2026-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conditiongenerale'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
