# Generated by Django 5.2.6 on 2026-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientprofile_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('MOBILE_MONEY', 'Mobile Money'), ('ESPECE', 'Espèce')], max_length=20, null=True),
        ),
    ]
