# Generated by Django 5.2.6 on 2026-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_commande_moyen_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='acompte_demande',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='modeledisponible',
            name='acompte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
