# Generated by Django 5.2.6 on 2026-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commande_acompte_demande_modeledisponible_acompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='type_paiement',
            field=models.CharField(blank=True, choices=[('TOTAL', 'Paiement total'), ('ACOMPTE', 'Acompte')], max_length=10, null=True),
        ),
    ]
