# Generated by Django 5.2.6 on 2026-08-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_wallet_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN MoMo'), ('orange_money', 'Orange Money'), ('wave', 'Wave')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESSFUL', 'Réussi'), ('FAILED', 'Échoué')], default='PENDING', max_length=16)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.offreabonnement')),
                ('professional_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='core.professionalprofile')),
            ],
        ),
    ]
