# Generated by Django 5.2.6 on 2026-09-24 11:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_modelecommande_image_tissu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelecommande',
            name='image_tissu',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_tissu_client),
        ),
    ]
